/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "var(--color-surface-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-secondary": "var(--color-on-secondary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-error": "var(--color-on-error)",
        "outline": "var(--color-outline)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "primary": "var(--color-primary)",
        "secondary-container": "var(--color-secondary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "tertiary": "var(--color-tertiary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-background": "var(--color-on-background)",
        "surface-tint": "var(--color-surface-tint)",
        "on-primary": "var(--color-on-primary)",
        "surface-variant": "var(--color-surface-variant)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "primary-container": "var(--color-primary-container)",
        "on-error-container": "var(--color-on-error-container)",
        "background": "var(--color-background)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-container": "var(--color-surface-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "secondary": "var(--color-secondary)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "error": "var(--color-error)",
        "error-container": "var(--color-error-container)",
        "surface-bright": "var(--color-surface-bright)",
        "surface": "var(--color-surface)",
        // Keep these if existing components use them:
        cf: {
          base: "var(--cf-base)",
          elevated: "var(--cf-elevated)",
          card: "var(--cf-card)",
          input: "var(--cf-input)",
          code: "var(--cf-code)",
          border: "var(--cf-border)",
          nav: "var(--cf-nav-border)",
          text: "var(--cf-text)",
          muted: "var(--cf-muted)",
        },
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["JetBrains Mono"]
      }
    },
  },
  plugins: [],
};
