export const CHAINS = [
  {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    color: "#627EEA",
    logoUrl: "/chains/ethereum.svg",
    evm: true,
    type: "evm",
    pros: ["Largest ecosystem", "High decentralization"],
    cons: ["High gas at peak times"],
    rpcLabel: "RPC_ETHEREUM",
  },
  {
    id: "polygon",
    name: "Polygon",
    symbol: "POL",
    color: "#8247E5",
    logoUrl: "/chains/polygon.svg",
    evm: true,
    type: "evm",
    pros: ["Low fees", "Fast confirmations"],
    cons: ["Bridge complexity"],
    rpcLabel: "RPC_POLYGON",
  },
  {
    id: "bnb",
    name: "BNB Chain",
    symbol: "BNB",
    color: "#F3BA2F",
    logoUrl: "/chains/bnb.svg",
    evm: true,
    type: "evm",
    pros: ["High throughput", "Cheap fees"],
    cons: ["Validator centralization concerns"],
    rpcLabel: "RPC_BNB",
  },
  {
    id: "avalanche",
    name: "Avalanche",
    symbol: "AVAX",
    color: "#E84142",
    logoUrl: "/chains/avalanche.svg",
    evm: true,
    type: "evm",
    pros: ["Fast finality", "Subnet architecture"],
    cons: ["Smaller liquidity than Ethereum"],
    rpcLabel: "RPC_AVALANCHE",
  },
  {
    id: "arbitrum",
    name: "Arbitrum",
    symbol: "ETH",
    color: "#28A0F0",
    logoUrl: "/chains/arbitrum.svg",
    evm: true,
    type: "evm",
    pros: ["Strong L2 ecosystem", "Low fees"],
    cons: ["Sequencer dependence"],
    rpcLabel: "RPC_ARBITRUM",
  },
  {
    id: "optimism",
    name: "Optimism",
    symbol: "ETH",
    color: "#FF0420",
    logoUrl: "/chains/optimism.svg",
    evm: true,
    type: "evm",
    pros: ["EVM compatible", "Low-cost txs"],
    cons: ["Sequencer dependence"],
    rpcLabel: "RPC_OPTIMISM",
  },
  {
    id: "base",
    name: "Base",
    symbol: "ETH",
    color: "#0052FF",
    logoUrl: "/chains/base.svg",
    evm: true,
    type: "evm",
    pros: ["Coinbase ecosystem", "Low fees"],
    cons: ["Centralization trade-offs"],
    rpcLabel: "RPC_BASE",
  },
  {
    id: "zksync",
    name: "zkSync Era",
    symbol: "ETH",
    color: "#8C8DFC",
    logoUrl: "/chains/zksync.svg",
    evm: true,
    type: "evm",
    pros: ["ZK security model", "Lower fees"],
    cons: ["Younger infra tooling"],
    rpcLabel: "RPC_ZKSYNC",
  },
  {
    id: "linea",
    name: "Linea",
    symbol: "ETH",
    color: "#121212",
    logoUrl: "/chains/linea.svg",
    evm: true,
    type: "evm",
    pros: ["EVM equivalence", "Good UX"],
    cons: ["Smaller ecosystem than top L2s"],
    rpcLabel: "RPC_LINEA",
  },
  {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    color: "#14F195",
    logoUrl: "/chains/solana.svg",
    evm: false,
    type: "solana",
    pros: ["Very fast", "Low tx cost"],
    cons: ["Different tooling model"],
    rpcLabel: "RPC_SOLANA",
  },
  {
    id: "sui",
    name: "Sui",
    symbol: "SUI",
    color: "#4DA2FF",
    logoUrl: "/chains/sui.svg",
    evm: false,
    type: "sui",
    pros: ["Parallel execution", "Good object model"],
    cons: ["Early ecosystem maturity"],
    rpcLabel: "RPC_SUI",
  },
  {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    color: "#F7931A",
    logoUrl: "/chains/bitcoin.svg",
    evm: false,
    type: "bitcoin",
    pros: ["Most secure chain", "Strong liquidity"],
    cons: ["Limited smart contract expressiveness"],
    rpcLabel: "RPC_BITCOIN",
  },
  {
    id: "cosmos",
    name: "Cosmos",
    symbol: "ATOM",
    color: "#2E7CFF",
    logoUrl: "/chains/cosmos.svg",
    evm: false,
    type: "cosmos",
    pros: ["Interchain messaging", "Rich SDK ecosystem"],
    cons: ["Multiple zone standards"],
    rpcLabel: "RPC_COSMOS",
  },
  {
    id: "near",
    name: "NEAR",
    symbol: "NEAR",
    color: "#00D1FF",
    logoUrl: "/chains/near.svg",
    evm: false,
    type: "near",
    pros: ["Fast finality", "Developer-friendly accounts"],
    cons: ["Different account model"],
    rpcLabel: "RPC_NEAR",
  },
  {
    id: "ton",
    name: "TON",
    symbol: "TON",
    color: "#00C2FF",
    logoUrl: "/chains/ton.svg",
    evm: false,
    type: "ton",
    pros: ["Fast", "Telegram ecosystem"],
    cons: ["Younger tooling"],
    rpcLabel: "RPC_TON",
  },
  {
    id: "tron",
    name: "Tron",
    symbol: "TRX",
    color: "#EF0000",
    logoUrl: "/chains/tron.svg",
    evm: false,
    type: "tron",
    pros: ["High throughput", "Large user base"],
    cons: ["Centralization concerns"],
    rpcLabel: "RPC_TRON",
  },
  {
    id: "starknet",
    name: "StarkNet",
    symbol: "ETH",
    color: "#8B5CF6",
    logoUrl: "/chains/starknet.svg",
    evm: false,
    type: "starknet",
    pros: ["ZK scaling", "Strong security model"],
    cons: ["Evolving tooling"],
    rpcLabel: "RPC_STARKNET",
  },
  {
    id: "aptos",
    name: "Aptos",
    symbol: "APT",
    color: "#0066FF",
    logoUrl: "/chains/aptos.svg",
    evm: false,
    type: "aptos",
    pros: ["Move language", "High throughput"],
    cons: ["Young ecosystem"],
    rpcLabel: "RPC_APTOS",
  },
];

export function getChain(id = "ethereum") {
  return CHAINS.find((c) => c.id === id) || CHAINS[0];
}
