/**
 * Canonical chain registry used across services and routes.
 */
export const CHAIN_REGISTRY = {
  ethereum: {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    chainId: 1,
    type: "evm",
    rpc: ["RPC_ETHEREUM", "RPC_ETHEREUM_FALLBACK"],
    explorer: "https://etherscan.io",
    gasModel: "eip1559",
    color: "#627EEA",
    logoUrl: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
    pros: ["Largest ecosystem", "High decentralization"],
    cons: ["High fees during congestion"],
    status: "up",
  },
  polygon: {
    id: "polygon",
    name: "Polygon",
    symbol: "POL",
    chainId: 137,
    type: "evm",
    rpc: ["RPC_POLYGON", "RPC_POLYGON_FALLBACK"],
    explorer: "https://polygonscan.com",
    gasModel: "eip1559",
    color: "#8247E5",
    logoUrl: "https://cryptologos.cc/logos/polygon-matic-logo.png",
    pros: ["Low fees", "EVM-compatible"],
    cons: ["More centralized validator set than Ethereum"],
    status: "up",
  },
  bnb: {
    id: "bnb",
    name: "BNB Chain",
    symbol: "BNB",
    chainId: 56,
    type: "evm",
    rpc: ["RPC_BNB", "RPC_BNB_FALLBACK"],
    explorer: "https://bscscan.com",
    gasModel: "legacy",
    color: "#F3BA2F",
    logoUrl: "https://cryptologos.cc/logos/bnb-bnb-logo.png",
    pros: ["High throughput", "Low fees"],
    cons: ["Higher centralization tradeoffs"],
    status: "up",
  },
  avalanche: {
    id: "avalanche",
    name: "Avalanche",
    symbol: "AVAX",
    chainId: 43114,
    type: "evm",
    rpc: ["RPC_AVALANCHE", "RPC_AVALANCHE_FALLBACK"],
    explorer: "https://snowtrace.io",
    gasModel: "eip1559",
    color: "#E84142",
    logoUrl: "https://cryptologos.cc/logos/avalanche-avax-logo.png",
    pros: ["Fast finality", "Subnet architecture"],
    cons: ["Smaller DeFi footprint than Ethereum"],
    status: "up",
  },
  arbitrum: {
    id: "arbitrum",
    name: "Arbitrum",
    symbol: "ETH",
    chainId: 42161,
    type: "evm",
    rpc: ["RPC_ARBITRUM", "RPC_ARBITRUM_FALLBACK"],
    explorer: "https://arbiscan.io",
    gasModel: "eip1559",
    color: "#28A0F0",
    logoUrl: "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
    pros: ["Large L2 ecosystem", "Low fees"],
    cons: ["Sequencer dependency"],
    status: "up",
  },
  optimism: {
    id: "optimism",
    name: "Optimism",
    symbol: "ETH",
    chainId: 10,
    type: "evm",
    rpc: ["RPC_OPTIMISM", "RPC_OPTIMISM_FALLBACK"],
    explorer: "https://optimistic.etherscan.io",
    gasModel: "eip1559",
    color: "#FF0420",
    logoUrl: "https://cryptologos.cc/logos/optimism-ethereum-op-logo.png",
    pros: ["Strong ecosystem incentives", "Low fees"],
    cons: ["Sequencer dependency"],
    status: "up",
  },
  base: {
    id: "base",
    name: "Base",
    symbol: "ETH",
    chainId: 8453,
    type: "evm",
    rpc: ["RPC_BASE", "RPC_BASE_FALLBACK"],
    explorer: "https://basescan.org",
    gasModel: "eip1559",
    color: "#0052FF",
    logoUrl: "https://cryptologos.cc/logos/base-base-logo.png",
    pros: ["Coinbase ecosystem distribution", "Low fees"],
    cons: ["Sequencer dependency"],
    status: "up",
  },
  zksync: {
    id: "zksync",
    name: "zkSync Era",
    symbol: "ETH",
    chainId: 324,
    type: "evm",
    rpc: ["RPC_ZKSYNC", "RPC_ZKSYNC_FALLBACK"],
    explorer: "https://era.zksync.network",
    gasModel: "eip1559",
    color: "#8C8DFC",
    logoUrl: "https://cryptologos.cc/logos/zksync-zk-logo.png",
    pros: ["ZK rollup security model", "Low fees"],
    cons: ["Tooling fragmentation"],
    status: "up",
  },
  linea: {
    id: "linea",
    name: "Linea",
    symbol: "ETH",
    chainId: 59144,
    type: "evm",
    rpc: ["RPC_LINEA", "RPC_LINEA_FALLBACK"],
    explorer: "https://lineascan.build",
    gasModel: "eip1559",
    color: "#121212",
    logoUrl: "https://cryptologos.cc/logos/consensys-linea-logo.png",
    pros: ["EVM equivalence", "Enterprise backing"],
    cons: ["Smaller liquidity than top L2s"],
    status: "up",
  },
  solana: {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    chainId: 101,
    type: "solana",
    rpc: ["RPC_SOLANA", "RPC_SOLANA_FALLBACK"],
    explorer: "https://solscan.io",
    gasModel: "compute-units",
    color: "#14F195",
    logoUrl: "https://cryptologos.cc/logos/solana-sol-logo.png",
    pros: ["High throughput", "Low fees"],
    cons: ["Historical uptime incidents"],
    status: "up",
  },
  sui: {
    id: "sui",
    name: "Sui",
    symbol: "SUI",
    chainId: 784,
    type: "sui",
    rpc: ["RPC_SUI", "RPC_SUI_FALLBACK"],
    explorer: "https://suivision.xyz",
    gasModel: "object-gas",
    color: "#4DA2FF",
    logoUrl: "https://cryptologos.cc/logos/sui-sui-logo.png",
    pros: ["Parallel execution model", "Fast finality"],
    cons: ["Younger ecosystem"],
    status: "up",
  },
  bitcoin: {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    chainId: 0,
    type: "bitcoin",
    rpc: ["RPC_BITCOIN", "RPC_BITCOIN_FALLBACK"],
    explorer: "https://mempool.space",
    gasModel: "sat-per-vbyte",
    color: "#F7931A",
    logoUrl: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
    pros: ["Most secure chain", "Deep liquidity"],
    cons: ["Limited programmability", "Lower throughput"],
    status: "up",
  },
  // Additional chains (placeholders / initial support)
  cosmos: {
    id: "cosmos",
    name: "Cosmos",
    symbol: "ATOM",
    chainId: 118,
    type: "cosmos",
    rpc: ["RPC_COSMOS"],
    explorer: "https://www.mintscan.io",
    gasModel: "gas",
    color: "#2E7CFF",
    logoUrl: "https://cryptologos.cc/logos/cosmos-atom-logo.png",
    pros: ["Interchain messaging", "Rich SDKs"],
    cons: ["Multiple SDKs across zones"],
    status: "unknown",
  },
  near: {
    id: "near",
    name: "NEAR",
    symbol: "NEAR",
    chainId: 1313161554,
    type: "near",
    rpc: ["RPC_NEAR"],
    explorer: "https://explorer.near.org",
    gasModel: "gas",
    color: "#00D1FF",
    logoUrl: "https://cryptologos.cc/logos/near-protocol-near-logo.png",
    pros: ["Fast finality", "Developer-friendly"],
    cons: ["Different account model"],
    status: "unknown",
  },
  ton: {
    id: "ton",
    name: "TON",
    symbol: "TON",
    chainId: 1001,
    type: "ton",
    rpc: ["RPC_TON"],
    explorer: "https://tonscan.org",
    gasModel: "gas",
    color: "#00C2FF",
    logoUrl: "https://cryptologos.cc/logos/toncoin-ton-logo.png",
    pros: ["Fast", "Mobile-first SDKs"],
    cons: ["Younger ecosystem"],
    status: "unknown",
  },
  tron: {
    id: "tron",
    name: "Tron",
    symbol: "TRX",
    chainId: 195,
    type: "tron",
    rpc: ["RPC_TRON"],
    explorer: "https://tronscan.org",
    gasModel: "energy",
    color: "#EF0000",
    logoUrl: "https://cryptologos.cc/logos/tron-trx-logo.png",
    pros: ["High throughput", "Large user base"],
    cons: ["Centralization concerns"],
    status: "unknown",
  },
  starknet: {
    id: "starknet",
    name: "StarkNet",
    symbol: "ETH",
    chainId: 0,
    type: "starknet",
    rpc: ["RPC_STARKNET"],
    explorer: "https://starkscan.co",
    gasModel: "l1+l2",
    color: "#8B5CF6",
    logoUrl: "https://cryptologos.cc/logos/starknet-stark-logo.png",
    pros: ["ZK proofs", "Scalability"],
    cons: ["Evolving tooling"],
    status: "unknown",
  },
  aptos: {
    id: "aptos",
    name: "Aptos",
    symbol: "APT",
    chainId: 2828,
    type: "aptos",
    rpc: ["RPC_APTOS"],
    explorer: "https://explorer.aptoslabs.com",
    gasModel: "gas",
    color: "#0066FF",
    logoUrl: "https://cryptologos.cc/logos/aptos-apt-logo.png",
    pros: ["Move language", "High throughput"],
    cons: ["Young ecosystem"],
    status: "unknown",
  },
};

export const SUPPORTED_CHAIN_IDS = Object.keys(CHAIN_REGISTRY);
