import { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Download, CheckCircle2, AlertCircle, Wallet, ExternalLink, ChevronRight } from "lucide-react";
import { createSiweMessage } from "viem/siwe";
import bs58 from "bs58";
import { walletSDK, CHAIN_CONFIG } from "../lib/walletSDK.js";
import { walletSupportsChain } from "../lib/walletChainMatrix.js";
import { api } from "../lib/api.js";

const STEPS = {
  SELECT_WALLET: "wallet",
  SELECT_CHAIN: "chain",
  SIGN_MESSAGE: "sign",
  SUCCESS: "success",
  ERROR: "error",
};

// Message must be generated by the backend to ensure nonce binding and prevent
// format drift across clients. We keep viem/siwe as a dependency for SDK usage
// elsewhere, but auth relies on the server-provided message.

export default function WalletModalV2({ open, onClose, onConnected, mode = "auth" }) {
  const [step, setStep] = useState(STEPS.SELECT_WALLET);
  const [wallets, setWallets] = useState([]);
  const [selectedWallet, setSelectedWallet] = useState(null);
  const [selectedChain, setSelectedChain] = useState("ethereum");
  const [preparedMessage, setPreparedMessage] = useState("");
  const [address, setAddress] = useState("");
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showMore, setShowMore] = useState(false);

  useEffect(() => {
    if (open) {
      setWallets(walletSDK.detectWallets());
      setStep(STEPS.SELECT_WALLET);
      setSelectedWallet(null);
      setSelectedChain("ethereum");
      setPreparedMessage("");
      setAddress("");
      setError(null);
    }
  }, [open]);

  const installedWallets = useMemo(() => wallets.filter((w) => w.installed), [wallets]);
  const moreWallets = useMemo(() => wallets.filter((w) => !w.installed), [wallets]);
  const evmConflicts = walletSDK.getWalletConflicts();
  const handleInstall = (url) => window.open(url, "_blank", "noopener,noreferrer");

  async function handleContinueToSign() {
    if (!selectedWallet) return;
    if (!walletSupportsChain(selectedWallet.id, selectedChain)) return;
    setLoading(true);
    setError(null);
    try {
      const result = await walletSDK.connect(selectedWallet.id, { chain: selectedChain });
      setAddress(result.address);
      if (mode === "auth") {
        const nonceRes = await api.get("/api/auth/wallet/nonce", {
          params: { address: result.address, chain: selectedChain },
        });
        setPreparedMessage(String(nonceRes.data?.message || ""));
        setStep(STEPS.SIGN_MESSAGE);
      } else {
        setStep(STEPS.SUCCESS);
        onConnected?.(result);
      }
    } catch (e) {
      setError({ message: e.message || "Connection failed" });
      setStep(STEPS.ERROR);
    } finally {
      setLoading(false);
    }
  }

  async function handleSignAndVerify() {
    setLoading(true);
    setError(null);
    try {
      const signature = await walletSDK.signMessage(preparedMessage);
      const verified = await api.post("/api/auth/wallet/verify", {
        message: preparedMessage,
        signature: typeof signature === "string" ? signature : bs58.encode(signature),
        chain: selectedChain,
      });
      setStep(STEPS.SUCCESS);
      if (mode === "auth") {
        setTimeout(async () => {
          onConnected?.({
            token: verified.data.token,
            user: verified.data.user,
            wallet: selectedWallet,
            chain: CHAIN_CONFIG[selectedChain],
            address,
          });
          onClose();
        }, 700);
      } else {
        setTimeout(() => {
          onConnected?.({
            wallet: selectedWallet,
            chain: selectedChain,
            address,
            signature,
          });
          onClose();
        }, 700);
      }
    } catch (e) {
      setError({ message: e.response?.data?.error || e.message || "Signature verification failed" });
      setStep(STEPS.ERROR);
    } finally {
      setLoading(false);
    }
  }

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          className="fixed inset-0 z-[200] flex items-center justify-center p-4"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          {/* Backdrop */}
          <motion.button
            type="button"
            className="absolute inset-0 bg-black/70 backdrop-blur-sm"
            aria-label="Close"
            onClick={onClose}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
          />

          {/* Modal */}
          <motion.div
            role="dialog"
            className="relative z-10 w-full max-w-md overflow-hidden rounded-2xl border border-cf-border bg-cf-card shadow-2xl"
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-center justify-between border-b border-cf-border px-6 py-4">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-purple-500 to-blue-500">
                  <Wallet className="h-5 w-5 text-white" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-cf-text">
                    {step === STEPS.SELECT_WALLET && "Connect Wallet"}
                    {step === STEPS.SELECT_CHAIN && "Select Network"}
                    {step === STEPS.SIGN_MESSAGE && "Sign Message"}
                    {step === STEPS.SUCCESS && "Connected!"}
                    {step === STEPS.ERROR && "Connection Failed"}
                  </h2>
                  <p className="text-xs text-cf-muted">
                    {step === STEPS.SELECT_WALLET && "Choose your preferred wallet"}
                    {step === STEPS.SELECT_CHAIN && `Supported by ${selectedWallet?.name}`}
                    {step === STEPS.SIGN_MESSAGE && "Review and sign full SIWE/SIWS message"}
                    {step === STEPS.SUCCESS && "You're all set"}
                    {step === STEPS.ERROR && "Something went wrong"}
                  </p>
                </div>
              </div>
              <button
                type="button"
                onClick={onClose}
                className="rounded-lg p-2 text-cf-muted hover:bg-cf-input hover:text-cf-text transition-colors"
                aria-label="Close modal"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Content */}
            <div className="p-6 max-h-[60vh] overflow-y-auto">
              {/* STEP 1: Select Wallet */}
              {step === STEPS.SELECT_WALLET && (
                <div className="space-y-4">
                  {/* Installed Wallets */}
                  {installedWallets.length > 0 && (
                    <div className="space-y-2">
                      <p className="text-xs font-medium uppercase tracking-wider text-cf-muted">
                        Installed Wallets
                      </p>
                      <div className="grid gap-2">
                        {installedWallets.map((wallet) => (
                          <button
                            key={wallet.id}
                            type="button"
                            onClick={() => {
                              setSelectedWallet(wallet);
                              setStep(STEPS.SELECT_CHAIN);
                            }}
                            className="flex items-center gap-3 rounded-xl border border-cf-border bg-cf-input px-4 py-3 text-left transition-all hover:border-purple-500 hover:bg-purple-500/5"
                          >
                            <img src={wallet.icon} alt={wallet.name} className="h-8 w-8 rounded-md object-contain" />
                            <div className="flex-1">
                              <p className="font-medium text-cf-text">{wallet.name}</p>
                              <p className="text-xs text-cf-muted">
                                {wallet.chains.length} networks supported
                              </p>
                            </div>
                            <ChevronRight className="h-5 w-5 text-cf-muted" />
                          </button>
                        ))}
                      </div>
                    </div>
                  )}

                  {evmConflicts.hasConflict && (
                    <div className="rounded-xl border border-amber-400/40 bg-amber-500/10 p-3 text-xs text-amber-200">
                      Multiple injected EVM wallets detected ({evmConflicts.count}). Choose wallet explicitly.
                    </div>
                  )}

                  {/* Not Installed Wallets */}
                  {moreWallets.length > 0 && (
                    <div className="space-y-2">
                      <p className="text-xs font-medium uppercase tracking-wider text-cf-muted">
                        Popular Wallets
                      </p>
                      <div className="grid gap-2">
                        {(showMore ? moreWallets : moreWallets.slice(0, 4)).map((wallet) => (
                          <button
                            key={wallet.id}
                            type="button"
                            onClick={() => handleInstall(wallet.installUrl)}
                            className="flex items-center gap-3 rounded-xl border border-dashed border-cf-border px-4 py-3 text-left transition-all hover:border-purple-500 hover:bg-purple-500/5"
                          >
                            <img src={wallet.icon} alt={wallet.name} className="h-8 w-8 rounded-md object-contain" />
                            <div className="flex-1">
                              <p className="font-medium text-cf-text">{wallet.name}</p>
                              <p className="text-xs text-purple-500">Click to install</p>
                            </div>
                            <Download className="h-4 w-4 text-cf-muted" />
                          </button>
                        ))}
                      </div>
                      {moreWallets.length > 4 && (
                        <button
                          type="button"
                          onClick={() => setShowMore((s) => !s)}
                          className="text-xs text-purple-400 hover:underline"
                        >
                          {showMore ? "Show less" : "Show more"}
                        </button>
                      )}
                    </div>
                  )}

                  {/* Help text */}
                  <div className="rounded-xl bg-cf-input p-4">
                    <p className="text-sm text-cf-muted">
                      <span className="text-cf-text font-medium">New to Web3?</span>{' '}
                      We recommend{' '}
                      <button 
                        onClick={() => handleInstall('https://metamask.io/download/')}
                        className="text-purple-500 hover:underline"
                      >
                        MetaMask
                      </button>{' '}
                      for EVM chains or{' '}
                      <button 
                        onClick={() => handleInstall('https://phantom.app/download')}
                        className="text-purple-500 hover:underline"
                      >
                        Phantom
                      </button>{' '}
                      for Solana.
                    </p>
                  </div>
                </div>
              )}

              {/* STEP 2: Select Chain */}
              {step === STEPS.SELECT_CHAIN && selectedWallet && (
                <div className="space-y-4">
                  <div className="flex items-center gap-2 rounded-xl bg-cf-input p-3">
                    <img src={selectedWallet.icon} alt={selectedWallet.name} className="h-8 w-8 rounded-md object-contain" />
                    <div>
                      <p className="font-medium text-cf-text">{selectedWallet.name}</p>
                      <p className="text-xs text-cf-muted">Select a network</p>
                    </div>
                    <button
                      onClick={() => setStep(STEPS.SELECT_WALLET)}
                      className="ml-auto text-xs text-purple-500 hover:underline"
                    >
                      Change
                    </button>
                  </div>

                  <div className="grid gap-2">
                    {Object.keys(CHAIN_CONFIG).map((chainKey) => {
                      const chain = CHAIN_CONFIG[chainKey];
                      if (!chain) return null;
                      const compatible = walletSupportsChain(selectedWallet.id, chainKey);
                      
                      return (
                        <button
                          key={chainKey}
                          type="button"
                          disabled={!compatible}
                          title={compatible ? `Use ${chain.name}` : `Not supported by ${selectedWallet.name}`}
                          onClick={() => setSelectedChain(chainKey)}
                          className={`flex items-center gap-3 rounded-xl border px-4 py-3 text-left transition-all ${
                            compatible
                              ? selectedChain === chainKey
                                ? "border-purple-500 bg-purple-500/10"
                                : "border-cf-border bg-cf-input hover:border-purple-500 hover:bg-purple-500/5"
                              : "border-cf-border/40 bg-cf-input/40 opacity-50 cursor-not-allowed"
                          }`}
                        >
                          <div 
                            className="h-8 w-8 rounded-full flex items-center justify-center text-white text-xs font-bold"
                            style={{ backgroundColor: chain.color }}
                          >
                            {chain.symbol.slice(0, 2)}
                          </div>
                          <div className="flex-1">
                            <p className="font-medium text-cf-text">{chain.name}</p>
                            <p className="text-xs text-cf-muted">
                              {chain.symbol} · gas {chain.gasBadge}
                            </p>
                          </div>
                          {!compatible ? (
                            <span className="text-[10px] text-cf-muted">Not supported</span>
                          ) : null}
                        </button>
                      );
                    })}
                  </div>
                  <button
                    type="button"
                    disabled={!walletSupportsChain(selectedWallet.id, selectedChain) || loading}
                    onClick={handleContinueToSign}
                    className="w-full rounded-xl bg-purple-600 px-4 py-3 text-sm font-medium text-white disabled:opacity-50"
                  >
                    {loading ? "Connecting..." : "Continue"}
                  </button>
                </div>
              )}

              {step === STEPS.SIGN_MESSAGE && (
                <div className="space-y-4">
                  <div className="rounded-xl border border-cf-border bg-cf-input p-4">
                    <p className="mb-2 text-xs uppercase tracking-wider text-cf-muted">Signature request</p>
                    <pre className="max-h-52 overflow-auto whitespace-pre-wrap text-xs text-cf-text">
                      {preparedMessage}
                    </pre>
                  </div>
                  <button
                    type="button"
                    onClick={handleSignAndVerify}
                    disabled={loading}
                    className="w-full rounded-xl bg-purple-600 px-4 py-3 text-sm font-medium text-white"
                  >
                    {loading ? "Waiting for signature..." : "Sign & verify"}
                  </button>
                </div>
              )}

              {/* STEP 4: Success */}
              {step === STEPS.SUCCESS && (
                <div className="flex flex-col items-center justify-center py-8">
                  <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-green-500/20">
                    <CheckCircle2 className="h-10 w-10 text-green-500" />
                  </div>
                  <p className="text-center text-lg font-medium text-cf-text">
                    Wallet Connected!
                  </p>
                  <p className="mt-2 text-center text-sm text-cf-muted">
                    {address?.slice(0, 6)}...{address?.slice(-4)}
                  </p>
                </div>
              )}

              {/* STEP 5: Error */}
              {step === STEPS.ERROR && error && (
                <div className="space-y-4">
                  <div className="flex flex-col items-center justify-center py-4">
                    <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-red-500/20">
                      <AlertCircle className="h-10 w-10 text-red-500" />
                    </div>
                    <p className="text-center text-lg font-medium text-cf-text">
                      Connection Failed
                    </p>
                    <p className="mt-2 max-w-xs text-center text-sm text-cf-muted">
                      {error.message}
                    </p>
                  </div>

                  {/* Install button if wallet not installed */}
                  {error.installUrl && (
                    <a
                      href={error.installUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center justify-center gap-2 rounded-xl bg-purple-600 px-4 py-3 text-sm font-medium text-white transition-colors hover:bg-purple-700"
                    >
                      <Download className="h-4 w-4" />
                      Install {selectedWallet?.name}
                      <ExternalLink className="h-4 w-4" />
                    </a>
                  )}

                  <div className="flex gap-2">
                    <button
                      onClick={() => setStep(STEPS.SELECT_WALLET)}
                      className="flex-1 rounded-xl border border-cf-border px-4 py-3 text-sm font-medium text-cf-muted transition-colors hover:bg-cf-input"
                    >
                      Choose Different Wallet
                    </button>
                    <button
                      onClick={() => {
                        setStep(STEPS.SELECT_WALLET);
                        setError(null);
                      }}
                      className="flex-1 rounded-xl bg-cf-input px-4 py-3 text-sm font-medium text-cf-text transition-colors hover:bg-cf-border"
                    >
                      Back
                    </button>
                  </div>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="border-t border-cf-border bg-cf-input px-6 py-3">
              <p className="text-center text-xs text-cf-muted">
                By connecting, you agree to our{' '}
                <a href="#" className="text-purple-500 hover:underline">Terms</a>
                {' '}and{' '}
                <a href="#" className="text-purple-500 hover:underline">Privacy Policy</a>
              </p>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
